[tool.poetry]
name = "python_coding_interview"
description = "Minimal Python environment for Jupyter Python practice"
version = "0.1.0"
authors = [
    "Cameron Rutherford"
]

[tool.poetry.dependencies]
python = ">=3.11"
jupyterlab = "*"
watermark = "*"
