project:
  type: website
  title: "Cameron's git-site"
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    # No need to render files in more than one place - this file is just included in another
    - "!quarto/old_resume.qmd"

format:
  html:
    theme: vapor

execute:
  freeze: auto

website:
  repo-url: https://github.com/CameronRutherford/CameronRutherford
  repo-actions: [edit]
  search:
    type: overlay
  navbar:
    search: true
    left:
      - quarto/resume.qmd
      - text: "Developer Guide"
        menu:
          - quarto/developer_guide/core.qmd
          - quarto/developer_guide/windows.qmd
      - text: "Presentations"
        menu:
          - quarto/presentations/stem-engagement/presentation.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/cam_rutherford_
        text: Quarto Twitter
      - icon: github
        href: https://github.com/CameronRutherford
        text: Quarto GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/robert-c-rutherford/
        text: LinkedIn
