project:
  type: website
  title: "Cameron's git-site"
  output-dir: docs

resources:
  - "presentations/math-magic/videos/*"

profile:
  group:
    - [base, cpp, python, devops]

format:
  html:
    theme: vapor
    default: true
    toc: true
    toc-depth: 4

execute:
  eval: false
  warning: true
  error: true
  echo: true
  cache: true
  freeze: true

website:
  repo-url: https://github.com/cameronrutherford/cameronrutherford
  repo-actions: [edit]
  search:
    type: overlay
  navbar:
    search: true
    left:
      - text: "Resume"
        file: resume/resume.qmd
      - text: "Site Configuration"
        menu:
          - config/devcontainer.qmd
          - config/github-actions.qmd
          - config/pre-commit.qmd
          - config/quickstart.qmd
          - config/quarto.qmd
      - text: "C++ Coding Interview"
        menu:
          - blog/cpp-coding-interview/00-gettingStarted.qmd
          - blog/cpp-coding-interview/01-testConfiguration.ipynb
          - blog/cpp-coding-interview/02-leetCode1095.ipynb
          - blog/cpp-coding-interview/03-leetCode2742.ipynb
      - text: "Python Coding Interview"
        menu:
          - blog/python-coding-interview/00-gettingStarted.qmd
          - blog/python-coding-interview/01-testConfiguration.ipynb
          - blog/python-coding-interview/02-leetCode1425.ipynb
          - blog/python-coding-interview/03-leetCode1793.ipynb
      - text: "CUDA Coding Interview"
        menu:
          - blog/CUDA-coding-interview/01-testConfiguration.ipynb
      - text: "Presentations"
        menu:
          - presentations/stem-engagement/presentation.qmd
          - presentations/math-magic/presentation.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/cam_rutherford_
        text: Quarto Twitter
      - icon: github
        href: https://github.com/cameronrutherford
        text: Quarto GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/robert-c-rutherford/
        text: LinkedIn
