project:
  type: website
  title: "Cameron's git-site"
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    # No need to render files in more than one place - this file is just included in another
    - "!resume/old_resume.qmd"
  post-render:
    - cp docs/README.md README.md

format:
  html:
    theme: vapor

execute:
  freeze: auto

website:
  repo-url: https://github.com/cameronrutherford/cameronrutherford
  repo-actions: [edit]
  search:
    type: overlay
  navbar:
    search: true
    left:
      - text: "Resume"
        file: resume/resume.qmd
      - text: "Site Configuration"
        menu:
          - config/devcontainer.qmd
          - config/github-actions.qmd
          - config/pre-commit.qmd
          - config/quickstart.qmd
          - config/quarto.qmd
      - text: "Presentations"
        menu:
          - presentations/stem-engagement/presentation.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/cam_rutherford_
        text: Quarto Twitter
      - icon: github
        href: https://github.com/cameronrutherford
        text: Quarto GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/robert-c-rutherford/
        text: LinkedIn
