project:
  type: website
  title: "Personal Repository"
  output-dir: docs
  post-render: 
    - cp docs/README.md .

format:
  html: 
    theme: vapor

execute:
  freeze: auto

website:
  navbar:
    search: true
    left:
      - text: "Home"
        file: personal-repo.qmd
      - text: "Resume"
        file: quarto/resume.qmd 
