---
filters:
    - include-code-files
format:
    html:
        default: true
        toc: true
        toc-depth: 4
    pdf:
       template: template.tex
       font: DejaVu Sans
       number-sections: false

title: HPC/ML/Q Research Software Engineer
name: (Robert) Cameron Rutherford

summary: Experienced HPC/ML/Q Research Software Engineer with 3+ years of expertise in deploying, optimizing, and teaching scientific software on diverse computing systems, including the world's largest supercomputers and quantum computers. Proven track record in end-to-end solution delivery, project leadership, and effective team coordination, while adept at managing social engineering challenges in software development processes.

contact:
    location: Manhattan, NY
    phone: (509) 218-1818
    email: cameron.rutherford@me.com
portfolio:
    linkedin: \href{https://www.linkedin.com/in/robert-c-rutherford/}{Robert C Rutherford}
    github: \href{https://github.com/cameronrutherford}{cameronrutherford}

---

::: {.content-visible when-format="pdf"}

# Experience

### Software Engineer II HPC/ML/Q, PNNL (Virtual): 2022 - Present

- Led Software Stack for ExaSGD project to Frontiner deployment (AMD based - current world #1)
- Facilitated deployment of ExaGO application to the cloud with ChatGPT integration
- Led software development of CUDA targetted Sparse GPU solver tailored for use case with HiOp
- MLOps internal offering leader developing containerisation and best practices community
- Assisted in Fortan (CPU) -> C++ (GPU) conversion for E3SM project through CI/CD

### Software Engineer I HPC/ML/Q, PNNL (Virtual): 2021 - 2022

- Led Privacy Preserving ML project to explore FHE, FL, DP and SMC applications in PNNL mission space
- Transitioned and successfully led ExaSGD software stack through development of AMD/HIP support
- Delivered internal tutorials on distributed machine learning with JAX and other internal MLOps offerings
- Led tutorials on using Qiskit, and trained other staff in Quantum through internal boot camp

### Post-Bachelors Research Associate HPC/ML/Q, PNNL (Virtual): 2020 - 2021

- Worked on open-source MLFlow offering to save lab $200k per project on WandB subscription
- Deployed ExaSGD software to Summit supercomputer (NVIDIA based - former world #1)
- Learned Quantum Computing basics to enable C2QA project research on IBM Quantum platform
- Worked in HPC support centre to deploy, debug and test various ML software stacks

### Tech Student 4 Optimization and Control Group, PNNL (Virtual): 2020

- Worked on RAJA linear algebra kernel development within HiOp for interface with ExaGO
- Learned CMake with Spack and implemented testing and packaging for ExaSGD software
- Profiled codebase on different GPU architectures and analyzed performance data
- Taught other developers about RAJA and CMake and delivered key kernels for project success

### Sports Events Coordinator, Whitworth University (Spokane, WA): 2019 - 2020
### IT Intern, Mac Management, Keysight Technologies (Colorado Springs, CO): 2018
### Calculus III Grader / Mathematics Tutor, Whitworth University (Spokane, WA): 2017, 2019
### Basketball Coach, S.G.S. & M.L.C (Sydney, AUS): 2015

# Publications

- S. Abhyankar, S. Peles, **R. Rutherford**, A. Mancinelli, **_Evaluation of AC optimal power flow on graphical processing units._** (IEEE PESGM 2021)
- S. Peles, M. Alam, A. J. Mancinelli, K. Perumalla, **R. C. Rutherford**, J. Ryan, C. G. Petra, **_Porting the Nonlinear Optimization Library HiOp to Accelerator-Based Hardware Architectures_** (arxiv 2021)

# Skills

```{=html}
<table>
    <thead>
        <tr>
            <th>C / C++17</th>
            <th>Python</th>
            <th>DevOps</th>
            <th>Machine Learning</th>
            <th>Other</th>
            <th>OtherII</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                <p> CUDA, HIP, MPI, OpenMP
                <p> CMake, Spack, pybind11
                <p> google [test/benchmark]
                <p> Performance Optimization
            </td>
            <td>
                <p> torch, Tensorflow, pyg
                <p> JAX, mpi4py, lightning
                <p> conda/mamba, poetry
                <p> qiskit, pytest, black
            </td>
            <td>
                <p> GitHub/GitLab CI/CD, git flow
                <p> k8s, ansible, SLURM/LSF
                <p> Containerization, MLOps
                <p> Quality Assurance, Agile
            </td>
            <td>
                <p> JupyterLab, VSCode, vim
                <p> tmux, google collab
                <p> dev-containers, jetbrains
                <p> IDE extensions, GUI tools
            </td>
            <td>
                <p> Tutorial Driven Dev.
                <p> .qmd, obsidian, LaTeX
                <p> RevealJS, docx, binder
                <p> Git[Hub/Lab] pages
            </td>
            <td>
                <p> Fully Homomorphic Encryption
                <p> Secure Multi-Party Computation
                <p> FL, DP, SSS, Cryptography
                <p> Rust, Go, Fortran
            </td>
        </tr>
    </tbody>
</table>
```

# Conferences

### Practice and Experience in Advanced Research Computing (PEARC): 2023
### Pacific Northwest National Laboratory (PNNL) Tech Fest: 2021-2023
### Energy Exascale Earth System Model (E3SM) Annual Meeting: 2023
### Sustainable Tools Ecosystem Project (STEP) East Coast Town Hall: 2023
### Exascale Computing Project (ECP) Annual Meeting: 2021-2023
### Pacific Northwest National Laboratory (PNNL) Innovation Summit: 2022
### Co-Design Centre for Quantum Advantage (C2QA) Annual Meeting: 2022

# Education

### Scientist & Engineer Rising Leader Learning Journey: 2023
### Cyber Security & National Security Seminar Series, PNNL: 2021 - 2022
### Whitworth University, B.S. Mathematics and Computer Science: G.P.A 3.9/4.0

- Outstanding Mathematics Major 2020
- ICPC Pacific Northwest Eastern Washington Site Winner 2018
- Howard R. Gage Memorial Scholarship 2017, 2018, 2019

# Other Activities

### Sustainable Horizons Institute HPC Mentor: 2022, 2023
### Quantum Information Science / HPC STEM Mentor: 2022 - Present
### Whitworth Chess Club President: 2019 - 2020
### Pine Codes Hackathon Winner: 2019
### SpokAnimal Shelter Volunteer: 2019
### Whitworth Men's Basketball Team: 2016 - 2019

:::

::: {.content-visible when-format="html"}

## Resume

```{=html}
<p class="text-center">
  <a class="btn btn-primary btn-lg cv-download" href="resume.pdf" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download current CV
  </a>
</p>

<iframe src="resume.pdf" height=500px style="border: 0.5px" position="absolute" top=0 left=0 width=100% height=100%></iframe>
```

## Old GitHub resume

Here is my old GitHub resume if you want to see what it used to look like - look how far I have come!

::: {.callout-caution collapse="true"}
## Click to expand and view my old resume!
{{< include old_resume.qmd >}}
:::

I saw this in a talk about plain text - the Australian flag is bugged on Windows. Since MSFT only added 3 flags to it's base character set, I decided it was a feature, not a bug, and will not be fixing it.

## Git Integration

Similar to the main README that is generted my `index.qmd`, I keep a pdf uploaded to git automatically. This is copied into the right place through the `post-render` stage of quarto, you just have to remember to commit the changes to git:

```{.YAML include="../_quarto.yml" start-line=10 end-line=12}
```

TODO: Write CI pipeline / pre-commit check that ensures that the main README and resume pdf are updated.

:::
