---
filters:
    - include-code-files
format:
    html:
        default: true
        toc: true
        toc-depth: 4
    pdf:
       template: template.tex
       font: DejaVu Sans
       number-sections: false

title: HPC/ML/Q Research Software Engineer
name: (Robert) Cameron Rutherford

summary: High Performance Computing (HPC) / Machine Learning (ML) / Quantum (Q) Research Software Engineer (RSE) with over 3 years of experience deploying, testing, optimizing and teaching people about scientific software and computing systems. I have worked on a wide variety of projects during my time at "the lab", and have had my code run on everywhere from the largest supercomputer in the world, to a novel quantum computer.

contact:
    location: Manhattan, NY
    phone: (509) 218-1818
    email: cameron.rutherford@me.com
portfolio:
    linkedin: \href{https://www.linkedin.com/in/robert-c-rutherford/}{Robert C Rutherford}
    github: \href{https://github.com/cameronrutherford}{cameronrutherford}

skills:
    - C / C++17:
        - CMake, Spack, CUDA / HIP
        - RAJA + Umpire / Kokkos
        - MPI, pybind11, toml11, spdlog
    - Python:
        - Pytorch, JAX, Distributed ML
        - conda, poetry, mamba
        - quarto, nbdev, qiskit
    - DevOps:
        - Docker, ghcr, S3
        - Singularity/Apptainer, charliecloud, podman
        - GitHub, GitLab, pre-commit
---

::: {.content-visible when-format="pdf"}

# Experience

### Software Engineer HPC/ML/Q, Pacific Northwest National Laboratory (Virtual): 2020 - Present

- Lead Software Stack for ExaSGD project through key Frontiner deployment to 8k nodes and 54k GPUs
- MLOps internal offering lead developing containerisation and best practices community
- On-boarding and support experience for both HPC Clusters and IBMQ systems
- Deployed ML software stack for various projects, and assisted in building continuous integration pipelines
- Lead Privacy Preserving ML project to explore FHE, FL, DP and SMC

### Sports Events Coordinator, Whitworth University (Spokane, WA): 2019 - 2020
### IT Intern, Mac Management, Keysight Technologies (Colorado Springs, CO): 2018
### Calculus III Grader / Mathematics Tutor, Whitworth University (Spokane, WA): 2017, 2019
### Basketball Coach, S.G.S. & M.L.C (Sydney, AUS): 2015

# Publications

- S. Abhyankar, S. Peles, **R. Rutherford**, A. Mancinelli, **_Evaluation of AC optimal power flow on graphical processing units._** (IEEE PESGM 2021)
- S. Peles, M. Alam, A. J. Mancinelli, K. Perumalla, **R. C. Rutherford**, J. Ryan, C. G. Petra, **_Porting the Nonlinear Optimization Library HiOp to Accelerator-Based Hardware Architectures_** (arxiv 2021)

# Conferences

### Practice and Experience in Advanced Research Computing (PEARC): 2023
### Pacific Northwest National Laboratory (PNNL) Tech Fest: 2021-2023
### Energy Exascale Earth System Model (E3SM) Annual Meeting: 2023
### Sustainable Tools Ecosystem Project (STEP) East Coast Town Hall: 2023
### Exascale Computing Project (ECP) Annual Meeting: 2021-2023
### Pacific Northwest National Laboratory (PNNL) Innovation Summit: 2022
### Co-Design Centre for Quantum Advantage (C2QA) Annual Meeting: 2022

# Education

### Scientist & Engineer Rising Leader Learning Journey: 2023
### Cyber Security & National Security Seminar Series, PNNL: 2021 - 2022
### Whitworth University, B.S. Mathematics and Computer Science: G.P.A 3.9/4.0

- Outstanding Mathematics Major 2020
- ICPC Pacific Northwest Eastern Washington Site Winner 2018
- Howard R. Gage Memorial Scholarship 2017, 2018, 2019

# Other Activities

### Sustainable Horizons Institute HPC Mentor: 2022, 2023
### Quantum Information Science / HPC STEM Mentor: 2022 - Present
### Whitworth Chess Club President: 2019 - 2020
### Pine Codes Hackathon Winner: 2019
### SpokAnimal Shelter Volunteer: 2019
### Whitworth Men's Basketball Team: 2016 - 2019

:::

::: {.content-visible when-format="html"}

## Resume

```{=html}
<p class="text-center">
  <a class="btn btn-primary btn-lg cv-download" href="resume.pdf" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download current CV
  </a>
</p>

<iframe src="resume.pdf" height=500px style="border: 0.5px" position="absolute" top=0 left=0 width=100% height=100%></iframe>
```

## Old GitHub resume

Here is my old GitHub resume if you want to see what it used to look like - look how far I have come!

::: {.callout-caution collapse="true"}
## Click to expand and view my old resume!
{{< include old_resume.qmd >}}
:::

I saw this in a talk about plain text - the Australian flag is bugged on Windows. Since MSFT only added 3 flags to it's base character set, I decided it was a feature, not a bug, and will not be fixing it.

## Git Integration

Similar to the main README that is generted my `index.qmd`, I keep a pdf uploaded to git automatically. This is copied into the right place through the `post-render` stage of quarto, you just have to remember to commit the changes to git:

```{.YAML include="../_quarto.yml" start-line=10 end-line=12}
```

TODO: Write CI pipeline / pre-commit check that ensures that the main README and resume pdf are updated.

:::
