---
title: "Windows Install Guide"
format:
    html:
        toc: true
---

While installing on MacOS seems trivial through installing Docker, working on Windows requires a WSL installation in order to work.

## Install Steps

1. https://learn.microsoft.com/en-gb/windows/wsl/install
    - Install WSL and a linux Distribution to run containers in
1. https://www.docker.com/
    - Install Docker, and create an account for personal use
1. https://code.visualstudio.com/blogs/2020/07/01/containers-wsl
    - Follow remaining steps in this Guide

## Debugging

### Dev-Container / VSCode Bugs

1. I personally had some quite mysterious bugs that were happening as a result of my storage being almost full. Cleaning that out helped, as well as the occasional restart. Symptoms of this included:
    - Docker failing to delete an old container. This is worthwhile doing as old containers can take up space
    - VSCode failing to build a dev-container. There were a variety of errors here - unable to start shell, unable to build container, unable to run on read-only file system...

### Windows relate bugs

1. I opened/edited some files with the file line ending in "windows mode", and so that appeared in git. I resolved this by installing and using pre-commit.

## Quarto Only

If you only want to install and use quarto locally, you can also just install Quarto yourself, and not render any code/interactive notebooks.
