name: 'Build Container'
on:
  pull_request:
    paths:
      - .devcontainer/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Quarto Render in Dev Container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/cameronrutherford/quarto-ci
          cacheFrom: ghcr.io/cameronrutherford/quarto-ci
          push: never
          # Make sure doc can render in container before we can pass build
          runCmd: quarto render
