name: 'Test Quarto Render w/ Container Build'
on:
  pull_request:
    paths:
      # Only runs when container config changes
      - .devcontainer/dev-build/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      # https://github.com/devcontainers/ci/issues/212
      # Have to do this manually becuase of issue with subfolders
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Build & start dev container
        run: devcontainer up --config .devcontainer/dev-build/devcontainer.json --workspace-folder .

      - name: Quartor render
        run: devcontainer exec --config .devcontainer/dev-build/devcontainer.json --workspace-folder . quarto render

      - uses: EndBug/add-and-commit@v9
        with:
          add: "['resume.pdf', 'README.md']"
          fetch: false
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: Update resume/README after quarto render
