name: 'Publish Container'
on:
  push:
    branches:
      - main
    paths:
      - .devcontainer/dev-build/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/devcontainers/ci/issues/212
      # Have to do this manually becuase of issue with subfolders
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Build and push devcontainer
        run: devcontainer build --push true --image-name ghcr.io/cameronrutherford/quarto-ci --config .devcontainer/dev-build/devcontainer.json --workspace-folder .
