name: 'build'
on: # rebuild any PRs and main branch changes
    # TODO - only run when Dockerfile changes
    # TODO - add another badge for pipeline
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/CameronRutherford/quarto-ci:dev
          # Make sure doc can render in container before pushing
          runCmd: quarto render
