name: 'Test Quarto Render w/ Container Build'
on:
  pull_request:
    paths:
      # Only runs when container config changes
      - .devcontainer/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build Dev Container and Quarto Render
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: quarto render
