name: 'Publish Container'
on:
  # Hoping this also runs when PRs are merged...
  push:
    branches:
      - main
    paths:
      - .devcontainer/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Dev Container Image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/cameronrutherford/quarto-ci
          cacheFrom: ghcr.io/cameronrutherford/quarto-ci
          # Make sure doc can render in container before pushing
          push: always
          # Don't run anything here since we assume it works
          # runCmd: quarto render
