name: 'GHCR Prebuit Dev-Container'
on:
  pull_request:
    paths:
      # Don't run when container is changed and we need to rebuild env
      - '!.devcontainer/**'

jobs:
  quarto-render:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/cameronrutherford/quarto-ci
        credentials:
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Quarto Render
        run: quarto render
