name: 'Test Quarto Render'
on:
  pull_request:

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/cameronrutherford/quarto-ci
        credentials:
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Quarto Render
        run: quarto render
